main = ".open-next/worker.js"
name = "injexpro-app"

compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_d2FybS1maW5jaC01MS5jbGVyay5hY2NvdW50cy5kZXYk"
CLERK_SIGN_IN_URL = "/sign-in"
CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_SUPABASE_URL = "https://hxrpavvwlrdoknndvqpu.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4cnBhdnZ3bHJkb2tubmR2cXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDUwOTYsImV4cCI6MjA2OTI4MTA5Nn0.YAPjhmWAYJuQ46t7fFB5HG0F58-txcwZHMmaoCEHZ6s"